// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeM2kqoeA4Y_5FN-t3Tjj3CehqSLWJ2fY',
    appId: '1:265615418152:web:3bde7e763b1b50a896a61d',
    messagingSenderId: '265615418152',
    projectId: 'shoppingapp-b47fe',
    authDomain: 'shoppingapp-b47fe.firebaseapp.com',
    storageBucket: 'shoppingapp-b47fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6NsvXzVOJJ-1uWb-EHg0RzZpC18WY7Q4',
    appId: '1:265615418152:android:d47621193529706e96a61d',
    messagingSenderId: '265615418152',
    projectId: 'shoppingapp-b47fe',
    storageBucket: 'shoppingapp-b47fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQkkh80ZUnaZdvGdFuc1QrVZGQLEBhhg',
    appId: '1:265615418152:ios:9115a2664e98c4e696a61d',
    messagingSenderId: '265615418152',
    projectId: 'shoppingapp-b47fe',
    storageBucket: 'shoppingapp-b47fe.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASQkkh80ZUnaZdvGdFuc1QrVZGQLEBhhg',
    appId: '1:265615418152:ios:306a645a2f3c697796a61d',
    messagingSenderId: '265615418152',
    projectId: 'shoppingapp-b47fe',
    storageBucket: 'shoppingapp-b47fe.appspot.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
